service:
  name: test-xray
  awsTracingConfig:
    mode: Active

provider:
  name: aws
  runtime: nodejs6.10  

functions:
  xrayFunc:
    handler: index.handler
    events:
      - http:
          path: /{any+}
          method: any  
